#!/usr/bin/env bash
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/i3/i3blocks.conf together with: ~/.config/i3/scripts/power-profiles

# script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)
# echo "$current_profile"
if [ $current_profile = "power-saver" ]
then
	echo "%{F#ff006f}"
elif [ $current_profile = "balanced" ]
then
	echo "%{F#ff3fdc}𢡄"
elif [ $current_profile = "performance" ]
then
	echo "%{F#be56ff}龍"
else
	echo "unknown"
fi
