#!/usr/bin/env bash
PRIMARY=#ffa8fc
HL=#ff00f7
RED=#fc265f
WHITE=#ffffff
BLUE=#3dc2ff
FONT=FiraCode\ Nerd\ Font
i3lock -k -B sigma --indicator --ring-color=$PRIMARY\ff --radius 100 --ring-width 10 --time-color=$WHITE\ff --time-str="%H:%M" --date-color=$WHITE\ff --keyhl-color=$HL\ff --bshl-color=$RED\ff --ringwrong-color=$RED\ff --insidewrong-color=$RED\cc --ringver-color=$BLUE\ff --insidever-color=$BLUE\cc --pass-media-keys --pass-screen-keys --pass-power-keys --pass-volume-keys --time-font=$FONT --date-font=$FONT --verif-font=$FONT --verif-font=$FONT --wrong-font=$FONT 
